apiVersion: v1
kind: Service
metadata:
  name: bside-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30003
  selector:
    app: bside-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bside-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tbside-backend
  template:
    metadata:
      labels:
        app: bside-backend
    spec:
      containers:
        - name: bside-backend
          image: 381491984567.dkr.ecr.us-east-1.amazonaws.com/bside-backend:7
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: taskboard-filesystem
                  key: port
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: taskboard-filesystem
                  key: db_source
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: taskboard-filesystem
                  key: db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: taskboard-filesystem
                  key: db_password
      imagePullSecrets:
        - name: regcred
